import React from 'react'

import { Helmet } from 'react-helmet'

import './home.css'

const Home = (props) => {
  return (
    <div className="home-container">
      <Helmet>
        <title>Studioj2y.ICU</title>
        <meta property="og:title" content="Studioj2y.ICU" />
      </Helmet>
      <main className="home-main">
        <div className="home-hero section-container">
          <div className="home-max-width max-content-container">
            <div className="home-heading-container">
              <h1 className="home-text">
                Welcome to StudioJ2y.ICU
                <span
                  dangerouslySetInnerHTML={{
                    __html: ' ',
                  }}
                />
              </h1>
              <span className="home-text01">
                <br></br>
                <span>
                  “Every word is like an unnecessary stain on silence and
                  nothingness.”
                  <span
                    dangerouslySetInnerHTML={{
                      __html: ' ',
                    }}
                  />
                </span>
                <br></br>
                <span> Samuel Beckett</span>
                <br></br>
              </span>
            </div>
            <div className="home-gallery">
              <div className="home-container1">
                <img
                  alt="image"
                  src="/rectangle%2095-1000w.png"
                  className="home-image"
                />
              </div>
              <div className="home-container2">
                <img
                  alt="image"
                  src="/rectangle%2095%20%5B1%5D-1000w.png"
                  className="home-image1"
                />
                <img
                  alt="image"
                  src="/rectangle%2095%20%5B2%5D-1000w.png"
                  className="home-image2"
                />
              </div>
              <div className="home-container3">
                <img
                  alt="image"
                  src="/rectangle%2095%20%5B3%5D-800h.png"
                  className="home-image3"
                />
                <div className="home-container4">
                  <img
                    alt="image"
                    src="/rectangle%2095%20%5B4%5D-1000w.png"
                    className="home-image4"
                  />
                  <img
                    alt="image"
                    src="/rectangle%2095%20%5B5%5D-1000w.png"
                    className="home-image5"
                  />
                </div>
              </div>
            </div>
            <span className="home-text07">
              All images are generated by Stable Diffusion with AI
            </span>
          </div>
        </div>
        <div className="home-portofolio section-container">
          <div className="home-max-width1 max-content-container">
            <div className="home-tab-selector-cards-container">
              <div className="home-speaker-card">
                <div className="home-image-container">
                  <img
                    alt="image"
                    src="/unsplash_qj15unotnh0-400h.png"
                    className="home-image6"
                  />
                  <div className="home-see-project-container">
                    <button className="button-secondary-white button button-md">
                      See project
                    </button>
                  </div>
                </div>
                <span className="home-first-name">ChatGPT</span>
              </div>
              <div className="home-speaker-card1">
                <div className="home-image-container1">
                  <img
                    alt="image"
                    src="/unsplash_wwqrpsnbpq4-400h.png"
                    className="home-image7"
                  />
                  <div className="home-see-project-container1">
                    <button className="button-secondary-white button button-md">
                      See project
                    </button>
                  </div>
                </div>
                <span className="home-first-name1">Stable Diffusion</span>
              </div>
              <div className="home-speaker-card2">
                <div className="home-image-container2">
                  <img
                    alt="image"
                    src="https://images.unsplash.com/photo-1622483767028-3f66f32aef97?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDEzfHxjb2NhJTIwY29sYXxlbnwwfHx8fDE2NDY5MjYyNTM&amp;ixlib=rb-1.2.1&amp;h=400"
                    className="home-image8"
                  />
                  <div className="home-see-project-container2">
                    <button className="button-secondary-white button button-md">
                      See project
                    </button>
                  </div>
                </div>
                <span className="home-first-name2">Gamma</span>
              </div>
            </div>
          </div>
          <span className="home-text08">
            <span>
              Want AI?
              <span
                dangerouslySetInnerHTML={{
                  __html: ' ',
                }}
              />
            </span>
            <br></br>
            <span>Get yours now</span>
          </span>
        </div>
      </main>
    </div>
  )
}

export default Home
